# Because of the low minutes / usage we have for OSS, we should only run the unit testing when a PR is submitted
name: Build and Test
on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -U --no-transfer-progress clean test